### ISSUE TITLE
Extend DynamoDB intel module

### ISSUE THREAD

**Issue by marco-lancini** [cartography-cncf/cartography#363]
We should probably extend the DynamoDB intel module to gather more information about tables, as at the moment we only collect the table name.

The DescribeTable API call returns a set of useful information:
* https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_DescribeTable.html

**Comment by tr-fteixeira** [comment]
hey @marco-lancini , was looking into picking this up to get a bit more familiar with the project, seems like this was already extended once and it has some extra details from the call you referenced, looking on the missing fields, not sure if all of them are valuable to have ingested. These are the fields supported, with an ✅  are the ones that are already in, i've added a ➕ on some that i thought could be useful to have. Thoughts? 

```
Table:
  ArchivalSummary: ➕ 
    ArchivalBackupArn: string
    ArchivalDateTime: number
    ArchivalReason: string
  AttributeDefinitions:
    - AttributeName: string
      AttributeType: string
  BillingModeSummary:  ➕ 
    BillingMode: string
    LastUpdateToPayPerRequestDateTime: number
  CreationDateTime: number ➕ 
  GlobalSecondaryIndexes: 
    - Backfilling: boolean
      IndexArn: string
      IndexName: string
      IndexSizeBytes: number
      IndexStatus: string
      ItemCount: number
      KeySchema:
        - AttributeName: string
          KeyType: string
      Projection:
        NonKeyAttributes:
          - string
        ProjectionType: string
      ProvisionedThroughput:
        LastDecreaseDateTime: number
        LastIncreaseDateTime: number
        numberOfDecreasesToday: number
        ReadCapacityUnits: number 
        WriteCapacityUnits: number 
  GlobalTableVersion: string
  ItemCount: number ✅ 
  KeySchema:
    - AttributeName: string
      KeyType: string
  LatestStreamArn: string ➕ 
  LatestStreamLabel: string ➕ 
  LocalSecondaryIndexes:
    - IndexArn: string
      IndexName: string
      IndexSizeBytes: number
      ItemCount: number
      KeySchema:
        - AttributeName: string
          KeyType: string
      Projection:
        NonKeyAttributes:
          - string
        ProjectionType: string
  ProvisionedThroughput:
    LastDecreaseDateTime: number
    LastIncreaseDateTime: number
    numberOfDecreasesToday: number
    ReadCapacityUnits: number ✅ 
    WriteCapacityUnits: number ✅ 
  Replicas:
    - GlobalSecondaryIndexes:
        - IndexName: string
          ProvisionedThroughputOverride:
            ReadCapacityUnits: number
      KMSMasterKeyId: string
      ProvisionedThroughputOverride:
        ReadCapacityUnits: number
      RegionName: string
      ReplicaInaccessibleDateTime: number
      ReplicaStatus: string
      ReplicaStatusDescription: string
      ReplicaStatusPercentProgress: string
  RestoreSummary: ➕ 
    RestoreDateTime: number
    RestoreInProgress: boolean
    SourceBackupArn: string
    SourceTableArn: string
  SSEDescription: ➕ 
    InaccessibleEncryptionDateTime: number
    KMSMasterKeyArn: string
    SSEType: string
    Status: string
  StreamSpecification: ➕ 
    StreamEnabled: boolean   
    StreamViewType: string  
  TableArn: string ✅ 
  TableId: string
  TableName: string ✅ 
  TableSizeBytes: number ✅ 
  TableStatus: string
```
